apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: customer2
  name: customer2
  selfLink: /api/v1/namespaces//services/master1
spec:
  ports:
  - protocol: TCP
    port: 6443
    name: https-port
  selector:
    run: customer2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
