apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: customer1
  name: customer1
  selfLink: /api/v1/namespaces//services/customer1
spec:
  ports:
  - protocol: TCP
    port: 6443
    name: https-port
  selector:
    run: customer1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
