apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: connect-cluster2
  name: connect-cluster2
spec:
  ports:
  - protocol: TCP
    port: 6443
    name: https-port
  selector:
    run: connect-cluster2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
