apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    run: connect-cluster1
  name: connect-cluster1
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/master1
spec:
  replicas: 3
  selector:
    matchLabels:
      run: connect-cluster1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: connect-cluster1
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-apiserver
        - --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
        - --runtime-config=api/v1
        - --allow-privileged=true
        - --bind-address=0.0.0.0
        - --secure-port=6443
        - --service-cluster-ip-range=10.100.0.0/24
        - --etcd-servers=http://etcd-client:2379
        - --etcd-prefix="/connect1/"
        - --advertise-address=85.222.238.234
        - --service-account-key-file=/opt/secrets/kube-serviceaccount.key
        - --service-account-lookup=false
        - --token-auth-file=/opt/tokens/tokens.csv
        - --authorization-policy-file=/opt/auth/auth-policy.json
        - --authorization-mode=ABAC
        - --client-ca-file=/opt/secrets/ca.pem
        - --tls-cert-file=/opt/secrets/apiserver.pem
        - --tls-private-key-file=/opt/secrets/apiserver-key.pem
        image: sethkarlo/kube-apiserver
        imagePullPolicy: Always
        name: kube-apiserver
        volumeMounts:
          - name: connect1-secrets
            mountPath: /opt/secrets
          - name: auth
            mountPath: /opt/auth
          - name: tokens
            mountPath: /opt/tokens
      - command:
        - /usr/local/bin/kube-controller-manager
        - --master=http://127.0.0.1:8080
        - --service-account-private-key-file=/opt/kube-serviceaccount.key/kube-serviceaccount.key
        - --leader-elect=true
        volumeMounts:
          - name: connect1-secrets
            mountPath: /opt/secrets
          - name: ca-certificates
            mountPath: /usr/share/ca-certificates
          - name: etc-ssl
            mountPath: /etc/ssl
        image: sethkarlo/kube-controller-manager
        imagePullPolicy: Always
        name: kube-controller-manager
      - command:
        - /usr/local/bin/kube-scheduler
        - --master=http://127.0.0.1:8080
        - --leader-elect=true
        image: sethkarlo/kube-scheduler
        imagePullPolicy: Always
        name: kube-scheduler
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: connect1-secrets
          secret:
            secretName: connect1-secrets
        - name: auth
          secret:
            secretName: auth
        - name: tokens
          secret:
            secretName: tokens
        - name: ca-certificates
          hostPath:
            path: /usr/share/ca-certificates
        - name: etc-ssl
          hostPath:
            path: /etc/ssl
   
status: {}
