apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-export
spec:
  capacity:
    storage: 200G
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.100.238.14
    path: "/exports"
